os: linux
dist: xenial

git:
  depth: 1

jobs:
  include:
    - stage: PHP
      language: php
      php: 7.2
      install: composer install
      cache:
        directories:
          - $HOME/.composer/cache
      script:
        - composer phing lint
        - composer phing phpcs
        - composer phing phpstan
        - composer phing test:ci
    - stage: TypeScript
      language: node_js
      node_js: 10.16.0
      cache:
        yarn: true
        directories:
          - node_modules
      script:
        - yarn eslint
        - yarn prettier
        - yarn test:ci

notifications:
  webhooks:
    - https://coveralls.io/webhook

