os: linux
dist: xenial

git:
  depth: 1

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
  - source $HOME/.nvm/nvm.sh
  - nvm install 10.16.0

before_script:
  - composer install
  - yarn install

jobs:
  include:
    - stage: PHP
      language: php
      php: 7.2
    - script: composer phing lint
      name: "Parallel Lint"
    - script: composer phing phpcs
      name: "CodeSniffer"
    - script: composer phing phpstan
      name: "PHPStan"
    - script: composer phing test:ci
      name: "Tests"
    - stage: TypeScript
      language: javascript
    - script: yarn eslint
      name: "ESLint"
    - script: yarn prettier
      name: "Prettier"
    - script: yarn test:ci
      name: "Tests"


cache:
  directories:
    - $HOME/.composer/cache
  yarn: true

notifications:
  webhooks:
    - https://coveralls.io/webhook

