os: linux
dist: xenial

git:
  depth: 1

jobs:
  include:
    - stage: PHP
      language: php
      php: 7.2
      install: composer install
      script:
        - composer phing lint
        - composer phing phpcs
        - composer phing phpstan
        - composer phing test:ci
    - stage: TypeScript
      language: node_js
      node_js: 10.16.0
      before_install:
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
    - script: yarn eslint
      name: "ESLint"
    - script: yarn prettier
      name: "Prettier"
    - script: yarn test:ci
      name: "Tests"


cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
  yarn: true

notifications:
  webhooks:
    - https://coveralls.io/webhook

