os: linux
dist: xenial
language: generic

php:
  - 7.2

git:
  depth: 1

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
  - source $HOME/.nvm/nvm.sh
  - nvm install 10.16.0

before_script:
  - composer install
  - yarn install

jobs:
  include:
    - stage: "PHP Parallel Lint"
      script: composer phing lint
    - stage: "PHP CodeSniffer"
      script: composer phing phpcs
    - stage: "PHPStan"
      script: composer phing phpstan
    - stage: "PHP Tests"
      script: composer phing test:ci
    - stage: "ESLint"
      script: yarn eslint
    - stage: Prettier
      script: yarn prettier
    - stage: "TS Tests"
      script: yart test:ci


cache:
  directories:
    - $HOME/.composer/cache
  yarn: true

notifications:
  webhooks:
    - https://coveralls.io/webhook

