name: CI
on:
  - push
  - pull_request

jobs:
  php:
    name: Php
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Php extensions cache
        id: phpcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: 7.4
          extensions: pcov
          key: v1
      - name: Cache Php extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.phpcache.outputs.dir }}
          key: ${{ steps.phpcache.outputs.key }}
          restore-keys: ${{ steps.phpcache.outputs.key }}
      - name: Setup Php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Setup composer cache
        id: composercache
        run: echo ::set-output name=dir::$(composer config cache-files-dir)
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Setup PCOV
        run: pecl install pcov
      - name: Install dependencies
        run: composer install
      - name: CI
        run: make ci
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: php
          path-to-lcov: ./temp/coverage/php/coverage.xml
          parallel: true
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup yarn cache
        id: yarncache
        run: echo ::set-output name=dir::$(yarn cache dir)
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarncache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hasFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install
      - name: CI
        run: yarn ci
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: typescript
          path-to-lcov: ./temp/coverage/ts/lcov.info
          parallel: true
  finish:
    runs-on: ubuntu-latest
    needs:
      - php
      - typescript
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true


